Repository walkccc/CLRS, pull requests merged in 2020-04, with the labels that each got.

#240 Update 8.3.md
  docs/Chap08/8.3.md
Labels: bug

#242 Update 4.4.md
  docs/Chap04/4.4.md
Labels: bug

#243 Update 6.1.md
  docs/Chap06/6.1.md
Labels: typo

#245 Update 25.3.md
  docs/Chap25/25.3.md
Labels: bug

#246 Update 26.5.md
  docs/Chap26/26.5.md
Labels: enhancement

#249 Update 9-1.md
  docs/Chap09/Problems/9-1.md
Labels: bug

#258 Update 4-5.md
  docs/Chap04/Problems/4-5.md
Labels: bug
